version: "3.9"

services:
  backend:
    build: .
    depends_on:
      - db
    ports:
      - 8080:8080
    container_name: try-cb-api
  
  frontend:
      build: "https://github.com/couchbaselabs/try-cb-frontend-v2.git#7.0"
      depends_on:
        - backend
      ports:
        - 8081:8081
      container_name: try-cb-fe
      entrypoint: ["wait-for-it", "backend:8080", "--timeout=400", "--strict", "--", "npm", "run", "serve"]

  db:
    image: couchbase/server-sandbox:7.0.0
    ports:
      - "8091-8095:8091-8095"
      - "11210:11210"
    expose: # expose ports 8091 & 8094 to other containers (mainly for backend)
      - "8091"
      - "8094"
    container_name: couchbase-sandbox-7.0.0

  test:
    build: "https://github.com/couchbaselabs/try-cb-test.git#main"
    depends_on:
      - backend
    environment:
      BACKEND_BASE_URL: http://backend:8080
    entrypoint: ["wait-for-it", "backend:8080", "--timeout=400", "--strict", "--", "bats", "travel-sample-backend.bats"]
    profiles:
      - test
